SET (ASSIMP_DEPS_SRC_DIR ${OE_CURRENT_DEPS_DIR}/assimp--2.0.863-sdk/code)
SET (ASSIMP_DEPS_INCLUDE_DIR ${OE_CURRENT_DEPS_DIR}/assimp--2.0.863-sdk/include)
SET (ASSIMP_DEPS_LIB_DIR ${OE_CURRENT_DEPS_BUILD_DIR}/code)
